### ISSUE TITLE
Need Modeller scripts and alignments

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/ecm29#1]
Hi @ichem001, I see your input comparative models in the `data` subdirectory, but what we're missing are the inputs to generate these in turn from experimental data - i.e. the Modeller scripts and alignment files you used. Can you add these to the repository please?

**Comment by benmwebb** [comment]
Still need these @ichem001  - if you can point me to the originals I can add them to the repository.

**Comment by ichem001** [comment]
Added folder with comparative modeling and updated the readme. 
If any additional info is needed, let me know.

**Comment by benmwebb** [comment]
Looks good, thanks!
