### ISSUE TITLE
Where are the final clustered models, and how many are there?

### ISSUE THREAD

**Issue by benmwebb** [integrativemodeling/ecm29#2]
@ichem001 In the paper you say you end up with 109,951 good scoring models, 60% of which end up in cluster 0 and 31% in cluster 1.

In the README you say the good scoring models are in `/salilab/park1/ilan/ECM29/ECM29_19S/Clustered_Models.tar.gz`. But there are 20000 models in there, not 109,951. Why the difference?

I assume that `Results/clustering/cluster.0.all.txt` lists all the models in cluster 0 (and there are 11980 lines in that file, which is 60% of 20000, so that makes sense). But what is the meaning of each line? It surely can't be the frame number because there are multiple runs. Is it just a simple index into `Clustered_Models.tar.gz` (and if so, in the order the files are found in that file, or in some sort of sorted order?)

**Comment by ichem001** [comment]
@benmwebb 
Some clarifications: 
I will add to the GitHub the data for the scores, which I realized are not there.
The test for convergence on the scores was performed on the 100k+ models as describes, but structural clustering could only be performed on a subset of those models. I randomly selected 20k models and then performed structural clustering on those. 

cluster.0.all.txt actually list an internal index for the model. I will be pushing also the list of models with the following format {traj_number}_{frame_number}.rmf3 -- hopefully that would be clearer.

**Comment by benmwebb** [comment]
Looks good, thanks!
